server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    username: root
    password: "010110"
    url: jdbc:mysql://localhost:3306/vchat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置 HikariCP 数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1

# mybatis 配置
mybatis:
  type-aliases-package: com.zyx.pojo
  mapper-locations: classpath:mapper/*.xml
  # 通用 Mapper配置
  mappers: com.zyx.utils.MyMapper
  not-empty: false
  identity: MYSQL

# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    - 123.57.218.70:22122